
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.wayoftheninjaforge.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.wayoftheninjaforge.block.Wall5wallBlock;
import net.mcreator.wayoftheninjaforge.block.Wall5trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Wall5stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Wall5slabBlock;
import net.mcreator.wayoftheninjaforge.block.Wall5pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Wall5fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Wall5buttonBlock;
import net.mcreator.wayoftheninjaforge.block.Wall5Block;
import net.mcreator.wayoftheninjaforge.block.Wall4wallBlock;
import net.mcreator.wayoftheninjaforge.block.Wall4trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Wall4stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Wall4slabBlock;
import net.mcreator.wayoftheninjaforge.block.Wall4pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Wall4fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Wall4buttonBlock;
import net.mcreator.wayoftheninjaforge.block.Wall4Block;
import net.mcreator.wayoftheninjaforge.block.Wall3wallBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3slabBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3buttonnBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3buttonBlock;
import net.mcreator.wayoftheninjaforge.block.Wall3Block;
import net.mcreator.wayoftheninjaforge.block.Wall2wallBlock;
import net.mcreator.wayoftheninjaforge.block.Wall2trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Wall2stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Wall2slabBlock;
import net.mcreator.wayoftheninjaforge.block.Wall2pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Wall2fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Wall2buttonBlock;
import net.mcreator.wayoftheninjaforge.block.Wall2Block;
import net.mcreator.wayoftheninjaforge.block.Wall1wallBlock;
import net.mcreator.wayoftheninjaforge.block.Wall1trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Wall1stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Wall1slabBlock;
import net.mcreator.wayoftheninjaforge.block.Wall1pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Wall1fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Wall1buttonBlock;
import net.mcreator.wayoftheninjaforge.block.Wall1Block;
import net.mcreator.wayoftheninjaforge.block.SagewoodLogBlock;
import net.mcreator.wayoftheninjaforge.block.SagewoodBlock;
import net.mcreator.wayoftheninjaforge.block.Roof3wallBlock;
import net.mcreator.wayoftheninjaforge.block.Roof3trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Roof3stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Roof3slabBlock;
import net.mcreator.wayoftheninjaforge.block.Roof3pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Roof3fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Roof3Block;
import net.mcreator.wayoftheninjaforge.block.Roof2wallBlock;
import net.mcreator.wayoftheninjaforge.block.Roof2trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Roof2stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Roof2slabBlock;
import net.mcreator.wayoftheninjaforge.block.Roof2pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Roof2fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Roof2buttonBlock;
import net.mcreator.wayoftheninjaforge.block.Roof2Block;
import net.mcreator.wayoftheninjaforge.block.Roof1wallBlock;
import net.mcreator.wayoftheninjaforge.block.Roof1trapdoorBlock;
import net.mcreator.wayoftheninjaforge.block.Roof1stairsBlock;
import net.mcreator.wayoftheninjaforge.block.Roof1slabBlock;
import net.mcreator.wayoftheninjaforge.block.Roof1pressureplateBlock;
import net.mcreator.wayoftheninjaforge.block.Roof1fenceBlock;
import net.mcreator.wayoftheninjaforge.block.Roof1buttonBlock;
import net.mcreator.wayoftheninjaforge.block.Roof1Block;
import net.mcreator.wayoftheninjaforge.block.GamaNoKuniPlant2Block;
import net.mcreator.wayoftheninjaforge.block.GamaNoKuniPlant1Block;
import net.mcreator.wayoftheninjaforge.block.Door3Block;
import net.mcreator.wayoftheninjaforge.block.Door2Block;
import net.mcreator.wayoftheninjaforge.block.Door1Block;
import net.mcreator.wayoftheninjaforge.WayOfTheNinjaForge1201Mod;

public class WayOfTheNinjaForge1201ModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, WayOfTheNinjaForge1201Mod.MODID);
	public static final RegistryObject<Block> WALL_1 = REGISTRY.register("wall_1", () -> new Wall1Block());
	public static final RegistryObject<Block> ROOF_1 = REGISTRY.register("roof_1", () -> new Roof1Block());
	public static final RegistryObject<Block> WALL_2 = REGISTRY.register("wall_2", () -> new Wall2Block());
	public static final RegistryObject<Block> WALL_3 = REGISTRY.register("wall_3", () -> new Wall3Block());
	public static final RegistryObject<Block> WALL_4 = REGISTRY.register("wall_4", () -> new Wall4Block());
	public static final RegistryObject<Block> WALL_5 = REGISTRY.register("wall_5", () -> new Wall5Block());
	public static final RegistryObject<Block> ROOF_2 = REGISTRY.register("roof_2", () -> new Roof2Block());
	public static final RegistryObject<Block> ROOF_3 = REGISTRY.register("roof_3", () -> new Roof3Block());
	public static final RegistryObject<Block> ROOF_1SLAB = REGISTRY.register("roof_1slab", () -> new Roof1slabBlock());
	public static final RegistryObject<Block> ROOF_1STAIRS = REGISTRY.register("roof_1stairs", () -> new Roof1stairsBlock());
	public static final RegistryObject<Block> ROOF_1FENCE = REGISTRY.register("roof_1fence", () -> new Roof1fenceBlock());
	public static final RegistryObject<Block> ROOF_1PRESSUREPLATE = REGISTRY.register("roof_1pressureplate", () -> new Roof1pressureplateBlock());
	public static final RegistryObject<Block> ROOF_1TRAPDOOR = REGISTRY.register("roof_1trapdoor", () -> new Roof1trapdoorBlock());
	public static final RegistryObject<Block> ROOF_1WALL = REGISTRY.register("roof_1wall", () -> new Roof1wallBlock());
	public static final RegistryObject<Block> ROOF_1BUTTON = REGISTRY.register("roof_1button", () -> new Roof1buttonBlock());
	public static final RegistryObject<Block> ROOF_2SLAB = REGISTRY.register("roof_2slab", () -> new Roof2slabBlock());
	public static final RegistryObject<Block> ROOF_2STAIRS = REGISTRY.register("roof_2stairs", () -> new Roof2stairsBlock());
	public static final RegistryObject<Block> ROOF_2FENCE = REGISTRY.register("roof_2fence", () -> new Roof2fenceBlock());
	public static final RegistryObject<Block> ROOF_2PRESSUREPLATE = REGISTRY.register("roof_2pressureplate", () -> new Roof2pressureplateBlock());
	public static final RegistryObject<Block> ROOF_2TRAPDOOR = REGISTRY.register("roof_2trapdoor", () -> new Roof2trapdoorBlock());
	public static final RegistryObject<Block> ROOF_2WALL = REGISTRY.register("roof_2wall", () -> new Roof2wallBlock());
	public static final RegistryObject<Block> ROOF_2BUTTON = REGISTRY.register("roof_2button", () -> new Roof2buttonBlock());
	public static final RegistryObject<Block> ROOF_3SLAB = REGISTRY.register("roof_3slab", () -> new Roof3slabBlock());
	public static final RegistryObject<Block> ROOF_3STAIRS = REGISTRY.register("roof_3stairs", () -> new Roof3stairsBlock());
	public static final RegistryObject<Block> ROOF_3FENCE = REGISTRY.register("roof_3fence", () -> new Roof3fenceBlock());
	public static final RegistryObject<Block> ROOF_3PRESSUREPLATE = REGISTRY.register("roof_3pressureplate", () -> new Roof3pressureplateBlock());
	public static final RegistryObject<Block> ROOF_3TRAPDOOR = REGISTRY.register("roof_3trapdoor", () -> new Roof3trapdoorBlock());
	public static final RegistryObject<Block> ROOF_3WALL = REGISTRY.register("roof_3wall", () -> new Roof3wallBlock());
	public static final RegistryObject<Block> WALL_3BUTTON = REGISTRY.register("wall_3button", () -> new Wall3buttonBlock());
	public static final RegistryObject<Block> WALL_1SLAB = REGISTRY.register("wall_1slab", () -> new Wall1slabBlock());
	public static final RegistryObject<Block> WALL_1STAIRS = REGISTRY.register("wall_1stairs", () -> new Wall1stairsBlock());
	public static final RegistryObject<Block> WALL_1FENCE = REGISTRY.register("wall_1fence", () -> new Wall1fenceBlock());
	public static final RegistryObject<Block> WALL_1PRESSUREPLATE = REGISTRY.register("wall_1pressureplate", () -> new Wall1pressureplateBlock());
	public static final RegistryObject<Block> WALL_1TRAPDOOR = REGISTRY.register("wall_1trapdoor", () -> new Wall1trapdoorBlock());
	public static final RegistryObject<Block> WALL_1WALL = REGISTRY.register("wall_1wall", () -> new Wall1wallBlock());
	public static final RegistryObject<Block> WALL_1BUTTON = REGISTRY.register("wall_1button", () -> new Wall1buttonBlock());
	public static final RegistryObject<Block> WALL_2SLAB = REGISTRY.register("wall_2slab", () -> new Wall2slabBlock());
	public static final RegistryObject<Block> WALL_2STAIRS = REGISTRY.register("wall_2stairs", () -> new Wall2stairsBlock());
	public static final RegistryObject<Block> WALL_2FENCE = REGISTRY.register("wall_2fence", () -> new Wall2fenceBlock());
	public static final RegistryObject<Block> WALL_2PRESSUREPLATE = REGISTRY.register("wall_2pressureplate", () -> new Wall2pressureplateBlock());
	public static final RegistryObject<Block> WALL_2TRAPDOOR = REGISTRY.register("wall_2trapdoor", () -> new Wall2trapdoorBlock());
	public static final RegistryObject<Block> WALL_2WALL = REGISTRY.register("wall_2wall", () -> new Wall2wallBlock());
	public static final RegistryObject<Block> WALL_2BUTTON = REGISTRY.register("wall_2button", () -> new Wall2buttonBlock());
	public static final RegistryObject<Block> WALL_3SLAB = REGISTRY.register("wall_3slab", () -> new Wall3slabBlock());
	public static final RegistryObject<Block> WALL_3STAIRS = REGISTRY.register("wall_3stairs", () -> new Wall3stairsBlock());
	public static final RegistryObject<Block> WALL_3FENCE = REGISTRY.register("wall_3fence", () -> new Wall3fenceBlock());
	public static final RegistryObject<Block> WALL_3PRESSUREPLATE = REGISTRY.register("wall_3pressureplate", () -> new Wall3pressureplateBlock());
	public static final RegistryObject<Block> WALL_3TRAPDOOR = REGISTRY.register("wall_3trapdoor", () -> new Wall3trapdoorBlock());
	public static final RegistryObject<Block> WALL_3WALL = REGISTRY.register("wall_3wall", () -> new Wall3wallBlock());
	public static final RegistryObject<Block> WALL_3BUTTONN = REGISTRY.register("wall_3buttonn", () -> new Wall3buttonnBlock());
	public static final RegistryObject<Block> WALL_4SLAB = REGISTRY.register("wall_4slab", () -> new Wall4slabBlock());
	public static final RegistryObject<Block> WALL_4STAIRS = REGISTRY.register("wall_4stairs", () -> new Wall4stairsBlock());
	public static final RegistryObject<Block> WALL_4FENCE = REGISTRY.register("wall_4fence", () -> new Wall4fenceBlock());
	public static final RegistryObject<Block> WALL_4PRESSUREPLATE = REGISTRY.register("wall_4pressureplate", () -> new Wall4pressureplateBlock());
	public static final RegistryObject<Block> WALL_4TRAPDOOR = REGISTRY.register("wall_4trapdoor", () -> new Wall4trapdoorBlock());
	public static final RegistryObject<Block> WALL_4WALL = REGISTRY.register("wall_4wall", () -> new Wall4wallBlock());
	public static final RegistryObject<Block> WALL_4BUTTON = REGISTRY.register("wall_4button", () -> new Wall4buttonBlock());
	public static final RegistryObject<Block> WALL_5SLAB = REGISTRY.register("wall_5slab", () -> new Wall5slabBlock());
	public static final RegistryObject<Block> WALL_5STAIRS = REGISTRY.register("wall_5stairs", () -> new Wall5stairsBlock());
	public static final RegistryObject<Block> WALL_5FENCE = REGISTRY.register("wall_5fence", () -> new Wall5fenceBlock());
	public static final RegistryObject<Block> WALL_5PRESSUREPLATE = REGISTRY.register("wall_5pressureplate", () -> new Wall5pressureplateBlock());
	public static final RegistryObject<Block> WALL_5TRAPDOOR = REGISTRY.register("wall_5trapdoor", () -> new Wall5trapdoorBlock());
	public static final RegistryObject<Block> WALL_5WALL = REGISTRY.register("wall_5wall", () -> new Wall5wallBlock());
	public static final RegistryObject<Block> WALL_5BUTTON = REGISTRY.register("wall_5button", () -> new Wall5buttonBlock());
	public static final RegistryObject<Block> DOOR_1 = REGISTRY.register("door_1", () -> new Door1Block());
	public static final RegistryObject<Block> DOOR_2 = REGISTRY.register("door_2", () -> new Door2Block());
	public static final RegistryObject<Block> DOOR_3 = REGISTRY.register("door_3", () -> new Door3Block());
	public static final RegistryObject<Block> SAGEWOOD_LOG = REGISTRY.register("sagewood_log", () -> new SagewoodLogBlock());
	public static final RegistryObject<Block> SAGEWOOD = REGISTRY.register("sagewood", () -> new SagewoodBlock());
	public static final RegistryObject<Block> GAMA_NO_KUNI_PLANT_1 = REGISTRY.register("gama_no_kuni_plant_1", () -> new GamaNoKuniPlant1Block());
	public static final RegistryObject<Block> GAMA_NO_KUNI_PLANT_2 = REGISTRY.register("gama_no_kuni_plant_2", () -> new GamaNoKuniPlant2Block());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
