
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.wayoftheninjaforge.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.wayoftheninjaforge.item.UzumakiarmorItem;
import net.mcreator.wayoftheninjaforge.item.TestScrollItem;
import net.mcreator.wayoftheninjaforge.item.TantowindItem;
import net.mcreator.wayoftheninjaforge.item.TantowaterItem;
import net.mcreator.wayoftheninjaforge.item.TantouchihaItem;
import net.mcreator.wayoftheninjaforge.item.TantostandardItem;
import net.mcreator.wayoftheninjaforge.item.TantoshadowItem;
import net.mcreator.wayoftheninjaforge.item.TantosenjuItem;
import net.mcreator.wayoftheninjaforge.item.TantomoonlightItem;
import net.mcreator.wayoftheninjaforge.item.TantolightingItem;
import net.mcreator.wayoftheninjaforge.item.TantofireItem;
import net.mcreator.wayoftheninjaforge.item.TantodragonfangItem;
import net.mcreator.wayoftheninjaforge.item.TantocursedItem;
import net.mcreator.wayoftheninjaforge.item.TantoanbuItem;
import net.mcreator.wayoftheninjaforge.item.TamagoyakiItem;
import net.mcreator.wayoftheninjaforge.item.TaijutsuarmorItem;
import net.mcreator.wayoftheninjaforge.item.TagremoteexplodeItem;
import net.mcreator.wayoftheninjaforge.item.TagexplosiveItem;
import net.mcreator.wayoftheninjaforge.item.SummoningScrollBeltItem;
import net.mcreator.wayoftheninjaforge.item.ShurikenwindItem;
import net.mcreator.wayoftheninjaforge.item.ShurikenstandardItem;
import net.mcreator.wayoftheninjaforge.item.ShurikenexplosiveItem;
import net.mcreator.wayoftheninjaforge.item.ShurikencursedItem;
import net.mcreator.wayoftheninjaforge.item.ShibukiItem;
import net.mcreator.wayoftheninjaforge.item.SenbonstandardItem;
import net.mcreator.wayoftheninjaforge.item.SenbonpoisonItem;
import net.mcreator.wayoftheninjaforge.item.SenbonfreezingItem;
import net.mcreator.wayoftheninjaforge.item.SenbeiItem;
import net.mcreator.wayoftheninjaforge.item.SasukearmorItem;
import net.mcreator.wayoftheninjaforge.item.SamuraiarmorItem;
import net.mcreator.wayoftheninjaforge.item.SamehadaItem;
import net.mcreator.wayoftheninjaforge.item.SakeItem;
import net.mcreator.wayoftheninjaforge.item.RyoItem;
import net.mcreator.wayoftheninjaforge.item.PuppettrainingItem;
import net.mcreator.wayoftheninjaforge.item.PuppetstandardItem;
import net.mcreator.wayoftheninjaforge.item.PuppetbladedItem;
import net.mcreator.wayoftheninjaforge.item.PuppersasoriItem;
import net.mcreator.wayoftheninjaforge.item.PupperkankuroItem;
import net.mcreator.wayoftheninjaforge.item.OnigiriItem;
import net.mcreator.wayoftheninjaforge.item.OdenItem;
import net.mcreator.wayoftheninjaforge.item.NuibariItem;
import net.mcreator.wayoftheninjaforge.item.NinjaSandalsItem;
import net.mcreator.wayoftheninjaforge.item.NarutobirthdaycakeItem;
import net.mcreator.wayoftheninjaforge.item.Musicdisk3Item;
import net.mcreator.wayoftheninjaforge.item.Musicdisk2Item;
import net.mcreator.wayoftheninjaforge.item.Musicdisk1Item;
import net.mcreator.wayoftheninjaforge.item.LogoItem;
import net.mcreator.wayoftheninjaforge.item.Logo4Item;
import net.mcreator.wayoftheninjaforge.item.Logo3Item;
import net.mcreator.wayoftheninjaforge.item.Logo2Item;
import net.mcreator.wayoftheninjaforge.item.KunaitrainingItem;
import net.mcreator.wayoftheninjaforge.item.KunaiteleporterItem;
import net.mcreator.wayoftheninjaforge.item.KunaismokeItem;
import net.mcreator.wayoftheninjaforge.item.KunaipoisonedItem;
import net.mcreator.wayoftheninjaforge.item.KunaimultibombaItem;
import net.mcreator.wayoftheninjaforge.item.KunaigoldenItem;
import net.mcreator.wayoftheninjaforge.item.KunaichidoriItem;
import net.mcreator.wayoftheninjaforge.item.KunaibombaItem;
import net.mcreator.wayoftheninjaforge.item.KunaiamaterasuItem;
import net.mcreator.wayoftheninjaforge.item.KunaiTrainingItemItem;
import net.mcreator.wayoftheninjaforge.item.KunaiStandartitemItem;
import net.mcreator.wayoftheninjaforge.item.KunaiMultiBombaItemItem;
import net.mcreator.wayoftheninjaforge.item.KunaiBombaItemItem;
import net.mcreator.wayoftheninjaforge.item.KubikiribochoItem;
import net.mcreator.wayoftheninjaforge.item.KibaswordsItem;
import net.mcreator.wayoftheninjaforge.item.KabutowariItem;
import net.mcreator.wayoftheninjaforge.item.JoninarmorItem;
import net.mcreator.wayoftheninjaforge.item.IchirakuramenItem;
import net.mcreator.wayoftheninjaforge.item.HiramekareiItem;
import net.mcreator.wayoftheninjaforge.item.GyozaItem;
import net.mcreator.wayoftheninjaforge.item.GrilletmeatItem;
import net.mcreator.wayoftheninjaforge.item.FumastandardItem;
import net.mcreator.wayoftheninjaforge.item.FumadarkItem;
import net.mcreator.wayoftheninjaforge.item.FumacollapsibleItem;
import net.mcreator.wayoftheninjaforge.item.FumachakraItem;
import net.mcreator.wayoftheninjaforge.item.ForeheadProtectorItem;
import net.mcreator.wayoftheninjaforge.item.DangoItem;
import net.mcreator.wayoftheninjaforge.item.DamageStickDEBUGItem;
import net.mcreator.wayoftheninjaforge.item.ChokutowindItem;
import net.mcreator.wayoftheninjaforge.item.ChokutowaterItem;
import net.mcreator.wayoftheninjaforge.item.ChokutouchihaItem;
import net.mcreator.wayoftheninjaforge.item.ChokutostandardItem;
import net.mcreator.wayoftheninjaforge.item.ChokutosamuraiItem;
import net.mcreator.wayoftheninjaforge.item.ChokutolightingItem;
import net.mcreator.wayoftheninjaforge.item.ChokutokusanagiItem;
import net.mcreator.wayoftheninjaforge.item.ChokutofireItem;
import net.mcreator.wayoftheninjaforge.item.ChokutoeliteItem;
import net.mcreator.wayoftheninjaforge.item.ChokutoearthItem;
import net.mcreator.wayoftheninjaforge.item.ChokutocursedItem;
import net.mcreator.wayoftheninjaforge.item.ChokutobloodItem;
import net.mcreator.wayoftheninjaforge.item.ChokutoabyssItem;
import net.mcreator.wayoftheninjaforge.item.ChakraGlovesItem;
import net.mcreator.wayoftheninjaforge.item.AnbuarmorItem;
import net.mcreator.wayoftheninjaforge.item.AkatsukiarmorItem;
import net.mcreator.wayoftheninjaforge.WayOfTheNinjaForge1201Mod;

public class WayOfTheNinjaForge1201ModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, WayOfTheNinjaForge1201Mod.MODID);
	public static final RegistryObject<Item> LOGO = REGISTRY.register("logo", () -> new LogoItem());
	public static final RegistryObject<Item> NINJA_SANDALS_BOOTS = REGISTRY.register("ninja_sandals_boots", () -> new NinjaSandalsItem.Boots());
	public static final RegistryObject<Item> FOREHEAD_PROTECTOR_HELMET = REGISTRY.register("forehead_protector_helmet", () -> new ForeheadProtectorItem.Helmet());
	public static final RegistryObject<Item> SUMMONING_SCROLL_BELT_LEGGINGS = REGISTRY.register("summoning_scroll_belt_leggings", () -> new SummoningScrollBeltItem.Leggings());
	public static final RegistryObject<Item> CHAKRA_GLOVES_CHESTPLATE = REGISTRY.register("chakra_gloves_chestplate", () -> new ChakraGlovesItem.Chestplate());
	public static final RegistryObject<Item> JONINARMOR_HELMET = REGISTRY.register("joninarmor_helmet", () -> new JoninarmorItem.Helmet());
	public static final RegistryObject<Item> JONINARMOR_CHESTPLATE = REGISTRY.register("joninarmor_chestplate", () -> new JoninarmorItem.Chestplate());
	public static final RegistryObject<Item> JONINARMOR_LEGGINGS = REGISTRY.register("joninarmor_leggings", () -> new JoninarmorItem.Leggings());
	public static final RegistryObject<Item> JONINARMOR_BOOTS = REGISTRY.register("joninarmor_boots", () -> new JoninarmorItem.Boots());
	public static final RegistryObject<Item> ANBUARMOR_HELMET = REGISTRY.register("anbuarmor_helmet", () -> new AnbuarmorItem.Helmet());
	public static final RegistryObject<Item> ANBUARMOR_CHESTPLATE = REGISTRY.register("anbuarmor_chestplate", () -> new AnbuarmorItem.Chestplate());
	public static final RegistryObject<Item> ANBUARMOR_LEGGINGS = REGISTRY.register("anbuarmor_leggings", () -> new AnbuarmorItem.Leggings());
	public static final RegistryObject<Item> ANBUARMOR_BOOTS = REGISTRY.register("anbuarmor_boots", () -> new AnbuarmorItem.Boots());
	public static final RegistryObject<Item> SAMURAIARMOR_HELMET = REGISTRY.register("samuraiarmor_helmet", () -> new SamuraiarmorItem.Helmet());
	public static final RegistryObject<Item> SAMURAIARMOR_CHESTPLATE = REGISTRY.register("samuraiarmor_chestplate", () -> new SamuraiarmorItem.Chestplate());
	public static final RegistryObject<Item> SAMURAIARMOR_LEGGINGS = REGISTRY.register("samuraiarmor_leggings", () -> new SamuraiarmorItem.Leggings());
	public static final RegistryObject<Item> SAMURAIARMOR_BOOTS = REGISTRY.register("samuraiarmor_boots", () -> new SamuraiarmorItem.Boots());
	public static final RegistryObject<Item> AKATSUKIARMOR_CHESTPLATE = REGISTRY.register("akatsukiarmor_chestplate", () -> new AkatsukiarmorItem.Chestplate());
	public static final RegistryObject<Item> AKATSUKIARMOR_LEGGINGS = REGISTRY.register("akatsukiarmor_leggings", () -> new AkatsukiarmorItem.Leggings());
	public static final RegistryObject<Item> AKATSUKIARMOR_BOOTS = REGISTRY.register("akatsukiarmor_boots", () -> new AkatsukiarmorItem.Boots());
	public static final RegistryObject<Item> UZUMAKIARMOR_CHESTPLATE = REGISTRY.register("uzumakiarmor_chestplate", () -> new UzumakiarmorItem.Chestplate());
	public static final RegistryObject<Item> UZUMAKIARMOR_LEGGINGS = REGISTRY.register("uzumakiarmor_leggings", () -> new UzumakiarmorItem.Leggings());
	public static final RegistryObject<Item> UZUMAKIARMOR_BOOTS = REGISTRY.register("uzumakiarmor_boots", () -> new UzumakiarmorItem.Boots());
	public static final RegistryObject<Item> TAIJUTSUARMOR_CHESTPLATE = REGISTRY.register("taijutsuarmor_chestplate", () -> new TaijutsuarmorItem.Chestplate());
	public static final RegistryObject<Item> TAIJUTSUARMOR_LEGGINGS = REGISTRY.register("taijutsuarmor_leggings", () -> new TaijutsuarmorItem.Leggings());
	public static final RegistryObject<Item> TAIJUTSUARMOR_BOOTS = REGISTRY.register("taijutsuarmor_boots", () -> new TaijutsuarmorItem.Boots());
	public static final RegistryObject<Item> SASUKEARMOR_CHESTPLATE = REGISTRY.register("sasukearmor_chestplate", () -> new SasukearmorItem.Chestplate());
	public static final RegistryObject<Item> SASUKEARMOR_LEGGINGS = REGISTRY.register("sasukearmor_leggings", () -> new SasukearmorItem.Leggings());
	public static final RegistryObject<Item> SASUKEARMOR_BOOTS = REGISTRY.register("sasukearmor_boots", () -> new SasukearmorItem.Boots());
	public static final RegistryObject<Item> RYO = REGISTRY.register("ryo", () -> new RyoItem());
	public static final RegistryObject<Item> ICHIRAKURAMEN = REGISTRY.register("ichirakuramen", () -> new IchirakuramenItem());
	public static final RegistryObject<Item> GYOZA = REGISTRY.register("gyoza", () -> new GyozaItem());
	public static final RegistryObject<Item> DANGO = REGISTRY.register("dango", () -> new DangoItem());
	public static final RegistryObject<Item> ONIGIRI = REGISTRY.register("onigiri", () -> new OnigiriItem());
	public static final RegistryObject<Item> ODEN = REGISTRY.register("oden", () -> new OdenItem());
	public static final RegistryObject<Item> SENBEI = REGISTRY.register("senbei", () -> new SenbeiItem());
	public static final RegistryObject<Item> TAMAGOYAKI = REGISTRY.register("tamagoyaki", () -> new TamagoyakiItem());
	public static final RegistryObject<Item> GRILLETMEAT = REGISTRY.register("grilletmeat", () -> new GrilletmeatItem());
	public static final RegistryObject<Item> SAKE = REGISTRY.register("sake", () -> new SakeItem());
	public static final RegistryObject<Item> NARUTOBIRTHDAYCAKE = REGISTRY.register("narutobirthdaycake", () -> new NarutobirthdaycakeItem());
	public static final RegistryObject<Item> MUSICDISK_1 = REGISTRY.register("musicdisk_1", () -> new Musicdisk1Item());
	public static final RegistryObject<Item> MUSICDISK_2 = REGISTRY.register("musicdisk_2", () -> new Musicdisk2Item());
	public static final RegistryObject<Item> MUSICDISK_3 = REGISTRY.register("musicdisk_3", () -> new Musicdisk3Item());
	public static final RegistryObject<Item> TEST_SCROLL = REGISTRY.register("test_scroll", () -> new TestScrollItem());
	public static final RegistryObject<Item> TAGEXPLOSIVE = REGISTRY.register("tagexplosive", () -> new TagexplosiveItem());
	public static final RegistryObject<Item> TAGREMOTEEXPLODE = REGISTRY.register("tagremoteexplode", () -> new TagremoteexplodeItem());
	public static final RegistryObject<Item> CHOKUTOSTANDARD = REGISTRY.register("chokutostandard", () -> new ChokutostandardItem());
	public static final RegistryObject<Item> CHOKUTOELITE = REGISTRY.register("chokutoelite", () -> new ChokutoeliteItem());
	public static final RegistryObject<Item> CHOKUTOUCHIHA = REGISTRY.register("chokutouchiha", () -> new ChokutouchihaItem());
	public static final RegistryObject<Item> CHOKUTOSAMURAI = REGISTRY.register("chokutosamurai", () -> new ChokutosamuraiItem());
	public static final RegistryObject<Item> CHOKUTOLIGHTING = REGISTRY.register("chokutolighting", () -> new ChokutolightingItem());
	public static final RegistryObject<Item> CHOKUTOFIRE = REGISTRY.register("chokutofire", () -> new ChokutofireItem());
	public static final RegistryObject<Item> CHOKUTOWIND = REGISTRY.register("chokutowind", () -> new ChokutowindItem());
	public static final RegistryObject<Item> CHOKUTOEARTH = REGISTRY.register("chokutoearth", () -> new ChokutoearthItem());
	public static final RegistryObject<Item> CHOKUTOWATER = REGISTRY.register("chokutowater", () -> new ChokutowaterItem());
	public static final RegistryObject<Item> CHOKUTOCURSED = REGISTRY.register("chokutocursed", () -> new ChokutocursedItem());
	public static final RegistryObject<Item> CHOKUTOBLOOD = REGISTRY.register("chokutoblood", () -> new ChokutobloodItem());
	public static final RegistryObject<Item> CHOKUTOABYSS = REGISTRY.register("chokutoabyss", () -> new ChokutoabyssItem());
	public static final RegistryObject<Item> CHOKUTOKUSANAGI = REGISTRY.register("chokutokusanagi", () -> new ChokutokusanagiItem());
	public static final RegistryObject<Item> KUNAITRAINING = REGISTRY.register("kunaitraining", () -> new KunaitrainingItem());
	public static final RegistryObject<Item> KUNAIBOMBA = REGISTRY.register("kunaibomba", () -> new KunaibombaItem());
	public static final RegistryObject<Item> KUNAIMULTIBOMBA = REGISTRY.register("kunaimultibomba", () -> new KunaimultibombaItem());
	public static final RegistryObject<Item> KUNAICHIDORI = REGISTRY.register("kunaichidori", () -> new KunaichidoriItem());
	public static final RegistryObject<Item> KUNAIAMATERASU = REGISTRY.register("kunaiamaterasu", () -> new KunaiamaterasuItem());
	public static final RegistryObject<Item> KUNAITELEPORTER = REGISTRY.register("kunaiteleporter", () -> new KunaiteleporterItem());
	public static final RegistryObject<Item> KUNAISMOKE = REGISTRY.register("kunaismoke", () -> new KunaismokeItem());
	public static final RegistryObject<Item> KUNAIPOISONED = REGISTRY.register("kunaipoisoned", () -> new KunaipoisonedItem());
	public static final RegistryObject<Item> KUNAIGOLDEN = REGISTRY.register("kunaigolden", () -> new KunaigoldenItem());
	public static final RegistryObject<Item> TANTOSTANDARD = REGISTRY.register("tantostandard", () -> new TantostandardItem());
	public static final RegistryObject<Item> TANTOANBU = REGISTRY.register("tantoanbu", () -> new TantoanbuItem());
	public static final RegistryObject<Item> TANTOUCHIHA = REGISTRY.register("tantouchiha", () -> new TantouchihaItem());
	public static final RegistryObject<Item> TANTOSENJU = REGISTRY.register("tantosenju", () -> new TantosenjuItem());
	public static final RegistryObject<Item> TANTOLIGHTING = REGISTRY.register("tantolighting", () -> new TantolightingItem());
	public static final RegistryObject<Item> TANTOWIND = REGISTRY.register("tantowind", () -> new TantowindItem());
	public static final RegistryObject<Item> TANTOFIRE = REGISTRY.register("tantofire", () -> new TantofireItem());
	public static final RegistryObject<Item> TANTOWATER = REGISTRY.register("tantowater", () -> new TantowaterItem());
	public static final RegistryObject<Item> TANTOCURSED = REGISTRY.register("tantocursed", () -> new TantocursedItem());
	public static final RegistryObject<Item> TANTOSHADOW = REGISTRY.register("tantoshadow", () -> new TantoshadowItem());
	public static final RegistryObject<Item> TANTODRAGONFANG = REGISTRY.register("tantodragonfang", () -> new TantodragonfangItem());
	public static final RegistryObject<Item> TANTOMOONLIGHT = REGISTRY.register("tantomoonlight", () -> new TantomoonlightItem());
	public static final RegistryObject<Item> PUPPETSTANDARD = REGISTRY.register("puppetstandard", () -> new PuppetstandardItem());
	public static final RegistryObject<Item> PUPPETTRAINING = REGISTRY.register("puppettraining", () -> new PuppettrainingItem());
	public static final RegistryObject<Item> PUPPETBLADED = REGISTRY.register("puppetbladed", () -> new PuppetbladedItem());
	public static final RegistryObject<Item> PUPPERKANKURO = REGISTRY.register("pupperkankuro", () -> new PupperkankuroItem());
	public static final RegistryObject<Item> PUPPERSASORI = REGISTRY.register("puppersasori", () -> new PuppersasoriItem());
	public static final RegistryObject<Item> SAMEHADA = REGISTRY.register("samehada", () -> new SamehadaItem());
	public static final RegistryObject<Item> KUBIKIRIBOCHO = REGISTRY.register("kubikiribocho", () -> new KubikiribochoItem());
	public static final RegistryObject<Item> SHIBUKI = REGISTRY.register("shibuki", () -> new ShibukiItem());
	public static final RegistryObject<Item> NUIBARI = REGISTRY.register("nuibari", () -> new NuibariItem());
	public static final RegistryObject<Item> KABUTOWARI = REGISTRY.register("kabutowari", () -> new KabutowariItem());
	public static final RegistryObject<Item> HIRAMEKAREI = REGISTRY.register("hiramekarei", () -> new HiramekareiItem());
	public static final RegistryObject<Item> KIBASWORDS = REGISTRY.register("kibaswords", () -> new KibaswordsItem());
	public static final RegistryObject<Item> FUMASTANDARD = REGISTRY.register("fumastandard", () -> new FumastandardItem());
	public static final RegistryObject<Item> FUMACHAKRA = REGISTRY.register("fumachakra", () -> new FumachakraItem());
	public static final RegistryObject<Item> FUMACOLLAPSIBLE = REGISTRY.register("fumacollapsible", () -> new FumacollapsibleItem());
	public static final RegistryObject<Item> FUMADARK = REGISTRY.register("fumadark", () -> new FumadarkItem());
	public static final RegistryObject<Item> SENBONSTANDARD = REGISTRY.register("senbonstandard", () -> new SenbonstandardItem());
	public static final RegistryObject<Item> SENBONPOISON = REGISTRY.register("senbonpoison", () -> new SenbonpoisonItem());
	public static final RegistryObject<Item> SENBONFREEZING = REGISTRY.register("senbonfreezing", () -> new SenbonfreezingItem());
	public static final RegistryObject<Item> SHURIKENSTANDARD = REGISTRY.register("shurikenstandard", () -> new ShurikenstandardItem());
	public static final RegistryObject<Item> SHURIKENWIND = REGISTRY.register("shurikenwind", () -> new ShurikenwindItem());
	public static final RegistryObject<Item> SHURIKENCURSED = REGISTRY.register("shurikencursed", () -> new ShurikencursedItem());
	public static final RegistryObject<Item> SHURIKENEXPLOSIVE = REGISTRY.register("shurikenexplosive", () -> new ShurikenexplosiveItem());
	public static final RegistryObject<Item> ROCKLEE_SPAWN_EGG = REGISTRY.register("rocklee_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.ROCKLEE, -13382656, -1, new Item.Properties()));
	public static final RegistryObject<Item> WALL_1 = block(WayOfTheNinjaForge1201ModBlocks.WALL_1);
	public static final RegistryObject<Item> ROOF_1 = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1);
	public static final RegistryObject<Item> WALL_2 = block(WayOfTheNinjaForge1201ModBlocks.WALL_2);
	public static final RegistryObject<Item> WALL_3 = block(WayOfTheNinjaForge1201ModBlocks.WALL_3);
	public static final RegistryObject<Item> WALL_4 = block(WayOfTheNinjaForge1201ModBlocks.WALL_4);
	public static final RegistryObject<Item> WALL_5 = block(WayOfTheNinjaForge1201ModBlocks.WALL_5);
	public static final RegistryObject<Item> ROOF_2 = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2);
	public static final RegistryObject<Item> ROOF_3 = block(WayOfTheNinjaForge1201ModBlocks.ROOF_3);
	public static final RegistryObject<Item> ROOF_1SLAB = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1SLAB);
	public static final RegistryObject<Item> ROOF_1STAIRS = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1STAIRS);
	public static final RegistryObject<Item> ROOF_1FENCE = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1FENCE);
	public static final RegistryObject<Item> ROOF_1PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1PRESSUREPLATE);
	public static final RegistryObject<Item> ROOF_1TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1TRAPDOOR);
	public static final RegistryObject<Item> ROOF_1WALL = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1WALL);
	public static final RegistryObject<Item> ROOF_1BUTTON = block(WayOfTheNinjaForge1201ModBlocks.ROOF_1BUTTON);
	public static final RegistryObject<Item> ROOF_2SLAB = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2SLAB);
	public static final RegistryObject<Item> ROOF_2STAIRS = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2STAIRS);
	public static final RegistryObject<Item> ROOF_2FENCE = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2FENCE);
	public static final RegistryObject<Item> ROOF_2PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2PRESSUREPLATE);
	public static final RegistryObject<Item> ROOF_2TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2TRAPDOOR);
	public static final RegistryObject<Item> ROOF_2WALL = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2WALL);
	public static final RegistryObject<Item> ROOF_2BUTTON = block(WayOfTheNinjaForge1201ModBlocks.ROOF_2BUTTON);
	public static final RegistryObject<Item> ROOF_3SLAB = block(WayOfTheNinjaForge1201ModBlocks.ROOF_3SLAB);
	public static final RegistryObject<Item> ROOF_3STAIRS = block(WayOfTheNinjaForge1201ModBlocks.ROOF_3STAIRS);
	public static final RegistryObject<Item> ROOF_3FENCE = block(WayOfTheNinjaForge1201ModBlocks.ROOF_3FENCE);
	public static final RegistryObject<Item> ROOF_3PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.ROOF_3PRESSUREPLATE);
	public static final RegistryObject<Item> ROOF_3TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.ROOF_3TRAPDOOR);
	public static final RegistryObject<Item> ROOF_3WALL = block(WayOfTheNinjaForge1201ModBlocks.ROOF_3WALL);
	public static final RegistryObject<Item> WALL_3BUTTON = block(WayOfTheNinjaForge1201ModBlocks.WALL_3BUTTON);
	public static final RegistryObject<Item> WALL_1SLAB = block(WayOfTheNinjaForge1201ModBlocks.WALL_1SLAB);
	public static final RegistryObject<Item> WALL_1STAIRS = block(WayOfTheNinjaForge1201ModBlocks.WALL_1STAIRS);
	public static final RegistryObject<Item> WALL_1FENCE = block(WayOfTheNinjaForge1201ModBlocks.WALL_1FENCE);
	public static final RegistryObject<Item> WALL_1PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.WALL_1PRESSUREPLATE);
	public static final RegistryObject<Item> WALL_1TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.WALL_1TRAPDOOR);
	public static final RegistryObject<Item> WALL_1WALL = block(WayOfTheNinjaForge1201ModBlocks.WALL_1WALL);
	public static final RegistryObject<Item> WALL_1BUTTON = block(WayOfTheNinjaForge1201ModBlocks.WALL_1BUTTON);
	public static final RegistryObject<Item> WALL_2SLAB = block(WayOfTheNinjaForge1201ModBlocks.WALL_2SLAB);
	public static final RegistryObject<Item> WALL_2STAIRS = block(WayOfTheNinjaForge1201ModBlocks.WALL_2STAIRS);
	public static final RegistryObject<Item> WALL_2FENCE = block(WayOfTheNinjaForge1201ModBlocks.WALL_2FENCE);
	public static final RegistryObject<Item> WALL_2PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.WALL_2PRESSUREPLATE);
	public static final RegistryObject<Item> WALL_2TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.WALL_2TRAPDOOR);
	public static final RegistryObject<Item> WALL_2WALL = block(WayOfTheNinjaForge1201ModBlocks.WALL_2WALL);
	public static final RegistryObject<Item> WALL_2BUTTON = block(WayOfTheNinjaForge1201ModBlocks.WALL_2BUTTON);
	public static final RegistryObject<Item> WALL_3SLAB = block(WayOfTheNinjaForge1201ModBlocks.WALL_3SLAB);
	public static final RegistryObject<Item> WALL_3STAIRS = block(WayOfTheNinjaForge1201ModBlocks.WALL_3STAIRS);
	public static final RegistryObject<Item> WALL_3FENCE = block(WayOfTheNinjaForge1201ModBlocks.WALL_3FENCE);
	public static final RegistryObject<Item> WALL_3PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.WALL_3PRESSUREPLATE);
	public static final RegistryObject<Item> WALL_3TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.WALL_3TRAPDOOR);
	public static final RegistryObject<Item> WALL_3WALL = block(WayOfTheNinjaForge1201ModBlocks.WALL_3WALL);
	public static final RegistryObject<Item> WALL_3BUTTONN = block(WayOfTheNinjaForge1201ModBlocks.WALL_3BUTTONN);
	public static final RegistryObject<Item> WALL_4SLAB = block(WayOfTheNinjaForge1201ModBlocks.WALL_4SLAB);
	public static final RegistryObject<Item> WALL_4STAIRS = block(WayOfTheNinjaForge1201ModBlocks.WALL_4STAIRS);
	public static final RegistryObject<Item> WALL_4FENCE = block(WayOfTheNinjaForge1201ModBlocks.WALL_4FENCE);
	public static final RegistryObject<Item> WALL_4PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.WALL_4PRESSUREPLATE);
	public static final RegistryObject<Item> WALL_4TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.WALL_4TRAPDOOR);
	public static final RegistryObject<Item> WALL_4WALL = block(WayOfTheNinjaForge1201ModBlocks.WALL_4WALL);
	public static final RegistryObject<Item> WALL_4BUTTON = block(WayOfTheNinjaForge1201ModBlocks.WALL_4BUTTON);
	public static final RegistryObject<Item> WALL_5SLAB = block(WayOfTheNinjaForge1201ModBlocks.WALL_5SLAB);
	public static final RegistryObject<Item> WALL_5STAIRS = block(WayOfTheNinjaForge1201ModBlocks.WALL_5STAIRS);
	public static final RegistryObject<Item> WALL_5FENCE = block(WayOfTheNinjaForge1201ModBlocks.WALL_5FENCE);
	public static final RegistryObject<Item> WALL_5PRESSUREPLATE = block(WayOfTheNinjaForge1201ModBlocks.WALL_5PRESSUREPLATE);
	public static final RegistryObject<Item> WALL_5TRAPDOOR = block(WayOfTheNinjaForge1201ModBlocks.WALL_5TRAPDOOR);
	public static final RegistryObject<Item> WALL_5WALL = block(WayOfTheNinjaForge1201ModBlocks.WALL_5WALL);
	public static final RegistryObject<Item> WALL_5BUTTON = block(WayOfTheNinjaForge1201ModBlocks.WALL_5BUTTON);
	public static final RegistryObject<Item> DOOR_1 = doubleBlock(WayOfTheNinjaForge1201ModBlocks.DOOR_1);
	public static final RegistryObject<Item> DOOR_2 = doubleBlock(WayOfTheNinjaForge1201ModBlocks.DOOR_2);
	public static final RegistryObject<Item> DOOR_3 = doubleBlock(WayOfTheNinjaForge1201ModBlocks.DOOR_3);
	public static final RegistryObject<Item> KONOHANINJA_SPAWN_EGG = REGISTRY.register("konohaninja_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KONOHANINJA, -16738048, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> NARUTO_SPAWN_EGG = REGISTRY.register("naruto_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.NARUTO, -26368, -16750849, new Item.Properties()));
	public static final RegistryObject<Item> SASUKE_SPAWN_EGG = REGISTRY.register("sasuke_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SASUKE, -10066177, -65536, new Item.Properties()));
	public static final RegistryObject<Item> SAKURA_SPAWN_EGG = REGISTRY.register("sakura_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SAKURA, -13057, -26113, new Item.Properties()));
	public static final RegistryObject<Item> KAKASHI_SPAWN_EGG = REGISTRY.register("kakashi_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KAKASHI, -1, -16751104, new Item.Properties()));
	public static final RegistryObject<Item> NEJI_SPAWN_EGG = REGISTRY.register("neji_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.NEJI, -1, -10066330, new Item.Properties()));
	public static final RegistryObject<Item> TENTEN_SPAWN_EGG = REGISTRY.register("tenten_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.TENTEN, -10092544, -10079488, new Item.Properties()));
	public static final RegistryObject<Item> GAI_SPAWN_EGG = REGISTRY.register("gai_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.GAI, -10027162, -16751104, new Item.Properties()));
	public static final RegistryObject<Item> KONOHA_ANBU_SPAWN_EGG = REGISTRY.register("konoha_anbu_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KONOHA_ANBU, -1, -39322, new Item.Properties()));
	public static final RegistryObject<Item> ASUMA_SPAWN_EGG = REGISTRY.register("asuma_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.ASUMA, -13408768, -6684673, new Item.Properties()));
	public static final RegistryObject<Item> SHIKAMARU_SPAWN_EGG = REGISTRY.register("shikamaru_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SHIKAMARU, -13395712, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> INO_SPAWN_EGG = REGISTRY.register("ino_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.INO, -6723841, -3355648, new Item.Properties()));
	public static final RegistryObject<Item> CHOJI_SPAWN_EGG = REGISTRY.register("choji_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.CHOJI, -6750208, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> SHINO_SPAWN_EGG = REGISTRY.register("shino_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SHINO, -16751104, -6684775, new Item.Properties()));
	public static final RegistryObject<Item> HINATA_SPAWN_EGG = REGISTRY.register("hinata_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.HINATA, -3355393, -1, new Item.Properties()));
	public static final RegistryObject<Item> KIBA_SPAWN_EGG = REGISTRY.register("kiba_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KIBA, -1, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> AKAMARU_SPAWN_EGG = REGISTRY.register("akamaru_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.AKAMARU, -1, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> KURENAI_SPAWN_EGG = REGISTRY.register("kurenai_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KURENAI, -1, -13108, new Item.Properties()));
	public static final RegistryObject<Item> DAMAGE_STICK_DEBUG = REGISTRY.register("damage_stick_debug", () -> new DamageStickDEBUGItem());
	public static final RegistryObject<Item> HASHIRAMA_SPAWN_EGG = REGISTRY.register("hashirama_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.HASHIRAMA, -1, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> TOBIRAMA_SPAWN_EGG = REGISTRY.register("tobirama_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.TOBIRAMA, -1, -16750849, new Item.Properties()));
	public static final RegistryObject<Item> HIRUZEN_SPAWN_EGG = REGISTRY.register("hiruzen_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.HIRUZEN, -1, -3407821, new Item.Properties()));
	public static final RegistryObject<Item> MINATO_SPAWN_EGG = REGISTRY.register("minato_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.MINATO, -3355648, -3407821, new Item.Properties()));
	public static final RegistryObject<Item> TSUNADE_SPAWN_EGG = REGISTRY.register("tsunade_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.TSUNADE, -13408768, -3355648, new Item.Properties()));
	public static final RegistryObject<Item> JIRAIYA_SPAWN_EGG = REGISTRY.register("jiraiya_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.JIRAIYA, -6750208, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> OROCHIMARU_SPAWN_EGG = REGISTRY.register("orochimaru_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.OROCHIMARU, -13434778, -1, new Item.Properties()));
	public static final RegistryObject<Item> SAI_SPAWN_EGG = REGISTRY.register("sai_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SAI, -13421773, -1, new Item.Properties()));
	public static final RegistryObject<Item> KABUTO_SPAWN_EGG = REGISTRY.register("kabuto_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KABUTO, -13434778, -10066330, new Item.Properties()));
	public static final RegistryObject<Item> KAZEKAGES_SHADOW_SPAWN_EGG = REGISTRY.register("kazekages_shadow_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KAZEKAGES_SHADOW, -52, -10066432, new Item.Properties()));
	public static final RegistryObject<Item> SUNA_NINJA_SPAWN_EGG = REGISTRY.register("suna_ninja_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SUNA_NINJA, -52, -52, new Item.Properties()));
	public static final RegistryObject<Item> RAIN_NINJA_SPAWN_EGG = REGISTRY.register("rain_ninja_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.RAIN_NINJA, -16750951, -16763956, new Item.Properties()));
	public static final RegistryObject<Item> AME_OPERATIVES_SPAWN_EGG = REGISTRY.register("ame_operatives_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.AME_OPERATIVES, -16750900, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> CLOUD_NINJA_SPAWN_EGG = REGISTRY.register("cloud_ninja_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.CLOUD_NINJA, -1, -13108, new Item.Properties()));
	public static final RegistryObject<Item> LIGHTNING_CORPS_SPAWN_EGG = REGISTRY.register("lightning_corps_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.LIGHTNING_CORPS, -16750900, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> PAIN_SPAWN_EGG = REGISTRY.register("pain_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.PAIN, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> NAGATO_SPAWN_EGG = REGISTRY.register("nagato_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.NAGATO, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> KONAN_SPAWN_EGG = REGISTRY.register("konan_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KONAN, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> ITACHIUCHIHA_SPAWN_EGG = REGISTRY.register("itachiuchiha_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.ITACHIUCHIHA, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> TOBI_SPAWN_EGG = REGISTRY.register("tobi_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.TOBI, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> ZETSU_SPAWN_EGG = REGISTRY.register("zetsu_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.ZETSU, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> DEIDARA_SPAWN_EGG = REGISTRY.register("deidara_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.DEIDARA, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> SASORI_SPAWN_EGG = REGISTRY.register("sasori_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SASORI, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> HIDAN_SPAWN_EGG = REGISTRY.register("hidan_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.HIDAN, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> KAKUZU_SPAWN_EGG = REGISTRY.register("kakuzu_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KAKUZU, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> KISAME_SPAWN_EGG = REGISTRY.register("kisame_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KISAME, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> JUZO_BIWA_SPAWN_EGG = REGISTRY.register("juzo_biwa_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.JUZO_BIWA, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> OBITO_SPAWN_EGG = REGISTRY.register("obito_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.OBITO, -16777216, -10092340, new Item.Properties()));
	public static final RegistryObject<Item> MADARA_SPAWN_EGG = REGISTRY.register("madara_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.MADARA, -16777216, -6750157, new Item.Properties()));
	public static final RegistryObject<Item> SAMUI_SPAWN_EGG = REGISTRY.register("samui_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SAMUI, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> KONOHAMARU_SPAWN_EGG = REGISTRY.register("konohamaru_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KONOHAMARU, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> ANKO_SPAWN_EGG = REGISTRY.register("anko_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.ANKO, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> IRUKA_SPAWN_EGG = REGISTRY.register("iruka_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.IRUKA, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> KUSHINA_SPAWN_EGG = REGISTRY.register("kushina_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KUSHINA, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> GAARA_SPAWN_EGG = REGISTRY.register("gaara_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.GAARA, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> KANKURO_SPAWN_EGG = REGISTRY.register("kankuro_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KANKURO, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> TEMARI_SPAWN_EGG = REGISTRY.register("temari_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.TEMARI, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> YUGITO_NII_SPAWN_EGG = REGISTRY.register("yugito_nii_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.YUGITO_NII, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> YAGURA_KARATACHI_SPAWN_EGG = REGISTRY.register("yagura_karatachi_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.YAGURA_KARATACHI, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> ROSHI_SPAWN_EGG = REGISTRY.register("roshi_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.ROSHI, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> HAN_SPAWN_EGG = REGISTRY.register("han_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.HAN, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> UTAKATA_SPAWN_EGG = REGISTRY.register("utakata_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.UTAKATA, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> FU_SPAWN_EGG = REGISTRY.register("fu_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.FU, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> KILLER_BEE_SPAWN_EGG = REGISTRY.register("killer_bee_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.KILLER_BEE, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> MU_SPAWN_EGG = REGISTRY.register("mu_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.MU, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> ONOKI_SPAWN_EGG = REGISTRY.register("onoki_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.ONOKI, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> RAIKAGE_SPAWN_EGG = REGISTRY.register("raikage_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.RAIKAGE, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> HOZUKI_SPAWN_EGG = REGISTRY.register("hozuki_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.HOZUKI, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> MEI_SPAWN_EGG = REGISTRY.register("mei_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.MEI, -103, -1, new Item.Properties()));
	public static final RegistryObject<Item> SHUKAKU_SPAWN_EGG = REGISTRY.register("shukaku_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.SHUKAKU, -16777216, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> LOGO_2 = REGISTRY.register("logo_2", () -> new Logo2Item());
	public static final RegistryObject<Item> LOGO_3 = REGISTRY.register("logo_3", () -> new Logo3Item());
	public static final RegistryObject<Item> LOGO_4 = REGISTRY.register("logo_4", () -> new Logo4Item());
	public static final RegistryObject<Item> SAGEWOOD_LOG = block(WayOfTheNinjaForge1201ModBlocks.SAGEWOOD_LOG);
	public static final RegistryObject<Item> SAGEWOOD = block(WayOfTheNinjaForge1201ModBlocks.SAGEWOOD);
	public static final RegistryObject<Item> GAMA_NO_KUNI_PLANT_1 = block(WayOfTheNinjaForge1201ModBlocks.GAMA_NO_KUNI_PLANT_1);
	public static final RegistryObject<Item> GAMA_NO_KUNI_PLANT_2 = block(WayOfTheNinjaForge1201ModBlocks.GAMA_NO_KUNI_PLANT_2);
	public static final RegistryObject<Item> TOAD_1_SPAWN_EGG = REGISTRY.register("toad_1_spawn_egg", () -> new ForgeSpawnEggItem(WayOfTheNinjaForge1201ModEntities.TOAD_1, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> KUNAI_STANDARTITEM = REGISTRY.register("kunai_standartitem", () -> new KunaiStandartitemItem());
	public static final RegistryObject<Item> KUNAI_TRAINING_ITEM = REGISTRY.register("kunai_training_item", () -> new KunaiTrainingItemItem());
	public static final RegistryObject<Item> KUNAI_BOMBA_ITEM = REGISTRY.register("kunai_bomba_item", () -> new KunaiBombaItemItem());
	public static final RegistryObject<Item> KUNAI_MULTI_BOMBA_ITEM = REGISTRY.register("kunai_multi_bomba_item", () -> new KunaiMultiBombaItemItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
